### ISSUE TITLE
build error, help

### ISSUE THREAD

**Issue by pplegends** [Zenithsiz/zbuild#1]
help 
i got this error when trying to build:
cargo install --path zbuild
error: failed to parse manifest at `/home/munf/git-build/zbuild/Cargo.toml`

Caused by:
  registry index was not found in any configuration: `filipejr`

How do I solve this?

I'm pretty new to Linux, so sorry if this is a dumb question.

**Comment by Zenithsiz** [comment]
Hey, thanks for the report.

The issue was due to the `npath` dependency being used from a custom registry. This was a hack that I needed a while ago, but I've removed it now in `0.1.6`, and it now uses their github repo (since it's not on `crates.io`).

I've tried it locally and it seems to build fine now without that registry, could you try it again? Thank you

**Comment by pplegends** [comment]
thanks, its build successfully now
